export const promptWordbanks = {
  pose: {
    safe: [
      "sitting on chair",
      "arms behind back",
      "indian style",
      "gill support",
      "leaning forward",
      "stretching",
      "sitting on the ground",
      "lying",
      "selfie",
      "pray",
      "yoga",
      "salute",
      "floating",
      "sitting",
      "hug self",
      "dynamic pose",
      "lying on back",
      "sitting on bed",
      "kneel",
      "princess carry",
      "walk",
      "standing",
      "on side",
      "hands on hips",
      "arms crossed",
      "hands in hair",
      "knees together",
      "hidden hands",
      "own hands clasped",
      "interlocked fingers",
      "arms up",
      "arms behind head",
      "crossed legs",
      "hugging own legs",
      "double peace hand",
      "arm up",
      "adjusting hair",
      "leg up",
      "clenched hands",
      "tying hair",
      "reaching",
      "arm support",
      "open hands",
    ],
    creative: [
      "w-sitting on the ground",
      "on stomach",
      "huddle, clasp knees",
      "skirt_lift",
      "fighting_stance",
      "wariza",
      "crossed_legs",
      "Skirt lift",
      "sitting on car",
      "squatting",
      "Lie on your side",
      "bent over",
      "half body under water",
      "Put hands around shoulders",
      "pigeon-toed",
      "presenting armpit",
      "outstretched arms",
      "m legs",
      "tail between legs",
      "unbuttoned clothes",
      "skindentation",
      "knees together feet apart",
      "spread toes",
      "feet up",
      "thick_thighs",
      "slim legs",
      "own hands together",
      "spread fingers",
      "cleavage",
      "plantar flexion",
      "sideboob",
      "arms behind back",
      "zombie pose",
      "platform heel",
      "outstretched arm",
      "legs apart",
      "knees to chest",
      "areola_slip",
      "looking over shoulder",
      "collarbone",
      "midriff",
      "hips",
      "bare legs",
      "stretching arms",
      "hands on lap",
      "bare arms",
      "bare shoulders",
      "knees apart",
      "bare back",
      "stretching leg",
      "arms around neck",
    ],
    nsfw: [
      "girl on top",
      "spread legs",
      "thigh gap",
      "arched back",
      "horse riding",
      "clothes_lift",
      "French kiss, proper kiss",
      "all fours",
      "groping",
      "looking through legs",
      "figure four sitting",
      "legs over head",
      "top-down bottom-up",
      "armpits",
      "prostrate, lie flat",
      "missionary position",
      "top-down_bottom-up",
      "trampling",
      "doggystyle",
      "standing split",
      "straddling",
      "girl_on_top,straddling",
      "fetal position",
      "open your legs wide",
      "jack-o' challenge",
      "hand on cortch",
      "puffy areolae",
      "papilla",
      "handjob gesture",
      "tiny tits",
      "ass visible through thighs",
      "hand between legs",
      "between legs",
      "big ass",
      "tiny_chest",
      "NSFW",
      "breast curtains",
      "navel",
      "clothed female nude male",
      "covering mouth",
      "breasts",
      "sitting on person",
      "huge breasts",
      "groin",
      "cameltoe",
      "open clothes",
      "ass",
      "thighs",
      "nipples",
      "areolae",
      "pelvis",
      "hand on own chest",
      "large breasts",
      "medium breasts",
      "small breasts",
      "arms tied",
      "legs tied",
    ],
  },
  adultInspiration: [
    "nsfw, extremely explicit",
    "completely nude",
    "uncensored",
    "topless, bottomless",
    "detailed nipples, detailed pussy",
    "extreme cleavage, spreading legs",
    "ahegao, drooling, cross-eyed",
    "sweat drops on body, body fluids, shiny skin",
    "bondage, shibari, tied up",
    "transparent clothing, see-through latex, wet shirt",
    "micro bikini, strings, pasties",
    "leash and collar, submissive pose",
    "breast grab, thigh grab",
    "cameltoe, camel toe",
    "nipple slip, panty pull",
    "squatting, all fours, doggy pose",
    "intense physical contact, groping",
    "tearing clothes, ripped clothes",
    "sensual biting, tongue out",
    "hypnotized eyes, empty eyes, mind break",
    "succubus wings, succubus tail, succubus outfit",
    "tentacles, monster girl elements",
    "glory hole, gloryhole (implied)",
    "breast pressing against glass/wall",
    "milk dripping, sticky liquids on skin",
    "chocolate body paint, whipped cream covering",
    "vibrator (implied), toys (implied)",
  ],
} as const;
